### ISSUE TITLE
CSS doesn't appear to be working correctly

### ISSUE THREAD

**Issue by yay101-zz** [blkqi/gmpd#4]
Chromium Version 72.0.3626.81 (Official Build) Manjaro Linux (64-bit)

I looked at the computed styles vs style sheet and couldn't see an obvious cause however i didn't look for long:
![screenshot2](https://user-images.githubusercontent.com/5609852/53457857-dc263c00-3a87-11e9-9207-20f867e0625f.png)

**Comment by corylk** [comment]
It looks like angular-material is missing, or at least the stylesheet. Did you `npm install` before running it? Do you have a `./node_modules` folder? Do you have `./node_modules/angular-material/angular-material.css`? Does the symlink at `./public/css/angular-material.css` appear to be valid? Thanks

**Comment by yay101-zz** [comment]
Still not sure what the issue was but a purge and reinstall fixed it. likely install hell on year old manjaro install.
